"""
Scanner Adapter System - Unified interface for all scanners

This module provides a standardized adapter pattern for integrating different types of scanners
(Go tools, inline Python scanners, external APIs) into the matthunder platform.
"""
import asyncio
import hashlib
import json
import os
import shutil
import subprocess
from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum
from pathlib import Path
from typing import Any, Optional
from uuid import UUID


class ScannerKind(str, Enum):
    """Scanner execution types"""
    GO = "go"  # Go-based CLI tools (subfinder, httpx, nuclei, etc.)
    INLINE = "inline"  # Python-based scanners
    UTILITY = "utility"  # Helper utilities
    INTEGRATION = "integration"  # External API integrations (Acunetix)


class ScannerCategory(str, Enum):
    """Scanner functional categories"""
    DISCOVERY = "discovery"  # Asset discovery, subdomain enumeration
    RECON = "recon"  # Active reconnaissance, probing
    VULNERABILITY = "vulnerability"  # Vulnerability scanning
    INFRASTRUCTURE = "infrastructure"  # Infrastructure analysis
    CONTENT = "content"  # Content discovery, crawling
    INTEGRATION = "integration"  # Third-party integrations


@dataclass
class ScannerInput:
    """Standardized scanner input contract"""
    target: str
    scan_id: str
    target_id: str
    user_id: str
    config: dict[str, Any] = field(default_factory=dict)
    output_dir: Optional[str] = None
    
    def to_dict(self) -> dict[str, Any]:
        return {
            "target": self.target,
            "scan_id": self.scan_id,
            "target_id": self.target_id,
            "user_id": self.user_id,
            "config": self.config,
            "output_dir": self.output_dir,
        }


@dataclass
class ScannerOutput:
    """Standardized scanner output contract"""
    success: bool
    findings: list[dict[str, Any]] = field(default_factory=list)
    evidence: list[dict[str, Any]] = field(default_factory=list)
    logs: list[dict[str, Any]] = field(default_factory=list)
    metrics: dict[str, Any] = field(default_factory=dict)
    error: Optional[str] = None
    
    def to_dict(self) -> dict[str, Any]:
        return {
            "success": self.success,
            "findings": self.findings,
            "evidence": self.evidence,
            "logs": self.logs,
            "metrics": self.metrics,
            "error": self.error,
        }


@dataclass
class FindingCandidate:
    """A potential finding generated by a scanner"""
    scanner: str
    severity: str  # critical, high, medium, low, info
    category: str
    title: str
    description: Optional[str] = None
    url: Optional[str] = None
    source_url: Optional[str] = None
    evidence: Optional[str] = None
    http_code: Optional[int] = None
    cve_id: Optional[str] = None
    cvss_score: Optional[float] = None
    remediation: Optional[str] = None
    metadata: Optional[dict[str, Any]] = None
    
    def to_dict(self) -> dict[str, Any]:
        return {
            "scanner": self.scanner,
            "severity": self.severity,
            "category": self.category,
            "title": self.title,
            "description": self.description,
            "url": self.url,
            "source_url": self.source_url,
            "evidence": self.evidence,
            "http_code": self.http_code,
            "cve_id": self.cve_id,
            "cvss_score": self.cvss_score,
            "remediation": self.remediation,
            "metadata": self.metadata,
        }


@dataclass
class EvidenceArtifact:
    """Evidence collected during scanning"""
    scanner: str
    file_path: str
    file_name: str
    file_type: str  # screenshot, http_response, source_code, output_file, etc.
    file_size: int
    file_hash: str  # SHA-256
    content_type: Optional[str] = None
    metadata: Optional[dict[str, Any]] = None
    
    def to_dict(self) -> dict[str, Any]:
        return {
            "scanner": self.scanner,
            "file_path": self.file_path,
            "file_name": self.file_name,
            "file_type": self.file_type,
            "file_size": self.file_size,
            "file_hash": self.file_hash,
            "content_type": self.content_type,
            "metadata": self.metadata,
        }


class ScannerAdapter(ABC):
    """
    Base class for all scanner adapters.
    
    All scanners must implement this interface to be integrated into the platform.
    This provides a unified execution contract regardless of the underlying implementation.
    """
    
    def __init__(self):
        self.name = self.__class__.__name__.lower().replace("adapter", "")
        self.display_name = self.name.title()
        self.description = ""
        self.category = ScannerCategory.VULNERABILITY
        self.kind = ScannerKind.INLINE
        self.timeout_seconds = 300
        self.rate_limit_rps = 10
    
    @abstractmethod
    def validate_input(self, input: ScannerInput) -> bool:
        """
        Validate scanner input before execution.
        
        Returns True if input is valid, False otherwise.
        Should check target format, required config fields, etc.
        """
        pass
    
    def check_scope(self, target: str, scope_rules: list[dict] = None) -> bool:
        """
        Check if target is within allowed scope.
        
        Uses scope rules to determine if scanning is permitted.
        Returns True if in scope, False if out of scope.
        """
        # Default implementation: allow all
        # Subclasses can override for specific scope checking
        if not scope_rules:
            return True
        
        for rule in scope_rules:
            rule_type = rule.get("rule_type")
            pattern = rule.get("pattern")
            is_allowed = rule.get("is_allowed", True)
            
            if rule_type == "domain":
                if target.endswith(pattern) or target == pattern:
                    return is_allowed
            elif rule_type == "regex":
                import re
                if re.match(pattern, target):
                    return is_allowed
        
        return True
    
    @abstractmethod
    async def execute(self, input: ScannerInput, context: dict[str, Any] = None) -> ScannerOutput:
        """
        Execute the scanner with the given input.
        
        This is the main execution method that must be implemented by all scanners.
        Returns a ScannerOutput with findings, evidence, logs, and metrics.
        """
        pass
    
    def collect_evidence(self, output: ScannerOutput, output_dir: str) -> list[EvidenceArtifact]:
        """
        Collect and hash evidence files from scanner output.
        
        Returns a list of EvidenceArtifact objects.
        """
        artifacts = []
        
        for evidence_item in output.evidence:
            file_path = evidence_item.get("file_path")
            if not file_path or not os.path.exists(file_path):
                continue
            
            try:
                file_size = os.path.getsize(file_path)
                file_name = os.path.basename(file_path)
                
                # Calculate SHA-256 hash
                sha256_hash = hashlib.sha256()
                with open(file_path, "rb") as f:
                    for byte_block in iter(lambda: f.read(4096), b""):
                        sha256_hash.update(byte_block)
                file_hash = sha256_hash.hexdigest()
                
                artifact = EvidenceArtifact(
                    scanner=self.name,
                    file_path=file_path,
                    file_name=file_name,
                    file_type=evidence_item.get("file_type", "output_file"),
                    file_size=file_size,
                    file_hash=file_hash,
                    content_type=evidence_item.get("content_type"),
                    metadata=evidence_item.get("metadata"),
                )
                artifacts.append(artifact)
            except Exception as e:
                # Log error but continue
                output.logs.append({
                    "level": "error",
                    "message": f"Failed to collect evidence from {file_path}: {str(e)}",
                    "timestamp": datetime.utcnow().isoformat(),
                })
        
        return artifacts
    
    def generate_findings(self, output: ScannerOutput) -> list[FindingCandidate]:
        """
        Generate finding candidates from scanner output.
        
        Returns a list of FindingCandidate objects.
        """
        findings = []
        
        for finding_data in output.findings:
            try:
                finding = FindingCandidate(
                    scanner=self.name,
                    severity=finding_data.get("severity", "info"),
                    category=finding_data.get("category", self.category.value),
                    title=finding_data.get("title", "Unknown Finding"),
                    description=finding_data.get("description"),
                    url=finding_data.get("url"),
                    source_url=finding_data.get("source_url"),
                    evidence=finding_data.get("evidence"),
                    http_code=finding_data.get("http_code"),
                    cve_id=finding_data.get("cve_id"),
                    cvss_score=finding_data.get("cvss_score"),
                    remediation=finding_data.get("remediation"),
                    metadata=finding_data.get("metadata"),
                )
                findings.append(finding)
            except Exception as e:
                output.logs.append({
                    "level": "error",
                    "message": f"Failed to generate finding: {str(e)}",
                    "timestamp": datetime.utcnow().isoformat(),
                })
        
        return findings
    
    def get_metadata(self) -> dict[str, Any]:
        """Get scanner metadata for registry"""
        return {
            "name": self.name,
            "display_name": self.display_name,
            "description": self.description,
            "category": self.category.value,
            "kind": self.kind.value,
            "timeout_seconds": self.timeout_seconds,
            "rate_limit_rps": self.rate_limit_rps,
        }


class GoToolAdapter(ScannerAdapter):
    """
    Adapter for Go-based CLI tools (subfinder, httpx, nuclei, etc.)
    
    Handles execution of external Go binaries with standardized input/output.
    """
    
    def __init__(self, binary_name: str, binary_path: Optional[str] = None):
        super().__init__()
        self.binary_name = binary_name
        self.binary_path = binary_path or shutil.which(binary_name)
        self.kind = ScannerKind.GO
    
    def validate_input(self, input: ScannerInput) -> bool:
        """Validate that binary exists and target is provided"""
        if not self.binary_path:
            return False
        if not input.target:
            return False
        return True
    
    async def execute(self, input: ScannerInput, context: dict[str, Any] = None) -> ScannerOutput:
        """Execute Go tool with timeout and capture output"""
        if not self.validate_input(input):
            return ScannerOutput(
                success=False,
                error=f"Invalid input or binary {self.binary_name} not found"
            )
        
        output = ScannerOutput(success=True)
        
        try:
            # Build command arguments (subclasses should override build_command_args)
            args = self.build_command_args(input)
            
            # Execute with timeout
            process = await asyncio.create_subprocess_exec(
                self.binary_path,
                *args,
                stdout=asyncio.subprocess.PIPE,
                stderr=asyncio.subprocess.PIPE,
                cwd=input.output_dir or os.getcwd(),
            )
            
            try:
                stdout, stderr = await asyncio.wait_for(
                    process.communicate(),
                    timeout=self.timeout_seconds
                )
                
                output.logs.append({
                    "level": "info",
                    "message": f"{self.binary_name} completed with exit code {process.returncode}",
                    "timestamp": datetime.utcnow().isoformat(),
                })
                
                # Parse output (subclasses should override parse_output)
                self.parse_output(stdout.decode(), stderr.decode(), output, input)
                
                if process.returncode != 0:
                    output.success = False
                    output.error = f"Exit code {process.returncode}: {stderr.decode()}"
                    
            except asyncio.TimeoutError:
                process.kill()
                output.success = False
                output.error = f"Scanner timed out after {self.timeout_seconds}s"
                output.logs.append({
                    "level": "error",
                    "message": output.error,
                    "timestamp": datetime.utcnow().isoformat(),
                })
        
        except Exception as e:
            output.success = False
            output.error = str(e)
            output.logs.append({
                "level": "error",
                "message": f"Execution failed: {str(e)}",
                "timestamp": datetime.utcnow().isoformat(),
            })
        
        return output
    
    def build_command_args(self, input: ScannerInput) -> list[str]:
        """
        Build command-line arguments for the Go tool.
        
        Subclasses should override this to provide tool-specific arguments.
        """
        return [input.target]
    
    def parse_output(self, stdout: str, stderr: str, output: ScannerOutput, input: ScannerInput):
        """
        Parse tool output and populate findings/evidence.
        
        Subclasses should override this to provide tool-specific parsing.
        """
        # Default: treat each line as a potential finding
        for line in stdout.strip().split("\n"):
            if line:
                output.findings.append({
                    "severity": "info",
                    "category": self.category.value,
                    "title": f"{self.display_name} output",
                    "evidence": line,
                })


class InlinePythonAdapter(ScannerAdapter):
    """
    Adapter for inline Python scanners.
    
    Wraps existing Python scanner functions into the adapter interface.
    """
    
    def __init__(self, scanner_func: callable, scanner_name: str):
        super().__init__()
        self.scanner_func = scanner_func
        self.name = scanner_name
        self.display_name = scanner_name.title()
        self.kind = ScannerKind.INLINE
    
    def validate_input(self, input: ScannerInput) -> bool:
        """Validate input for inline scanner"""
        return bool(input.target)
    
    async def execute(self, input: ScannerInput, context: dict[str, Any] = None) -> ScannerOutput:
        """Execute inline Python scanner function"""
        if not self.validate_input(input):
            return ScannerOutput(
                success=False,
                error="Invalid input"
            )
        
        output = ScannerOutput(success=True)
        
        try:
            # Run scanner function in thread pool to avoid blocking
            loop = asyncio.get_event_loop()
            result = await loop.run_in_executor(
                None,
                self.scanner_func,
                input.target,
                input.config
            )
            
            # Parse result
            if isinstance(result, list):
                for item in result:
                    if isinstance(item, dict):
                        output.findings.append(item)
            elif isinstance(result, dict):
                if "findings" in result:
                    output.findings.extend(result["findings"])
                if "evidence" in result:
                    output.evidence.extend(result["evidence"])
            
            output.logs.append({
                "level": "info",
                "message": f"{self.name} completed successfully",
                "timestamp": datetime.utcnow().isoformat(),
            })
        
        except Exception as e:
            output.success = False
            output.error = str(e)
            output.logs.append({
                "level": "error",
                "message": f"Scanner failed: {str(e)}",
                "timestamp": datetime.utcnow().isoformat(),
            })
        
        return output


class ScannerRegistry:
    """
    Central registry for all scanner adapters.
    
    Provides discovery, instantiation, and metadata management for scanners.
    """
    
    def __init__(self):
        self._adapters: dict[str, type[ScannerAdapter]] = {}
        self._instances: dict[str, ScannerAdapter] = {}
    
    def register(self, name: str, adapter_class: type[ScannerAdapter]):
        """Register a scanner adapter class"""
        self._adapters[name] = adapter_class
    
    def register_instance(self, name: str, adapter: ScannerAdapter):
        """Register a pre-instantiated scanner adapter"""
        self._instances[name] = adapter
    
    def get(self, name: str) -> Optional[ScannerAdapter]:
        """Get a scanner adapter instance by name"""
        # Check instances first
        if name in self._instances:
            return self._instances[name]
        
        # Check classes and instantiate
        if name in self._adapters:
            adapter = self._adapters[name]()
            self._instances[name] = adapter
            return adapter
        
        return None
    
    def list_scanners(self) -> list[dict[str, Any]]:
        """List all registered scanners with metadata"""
        scanners = []
        
        # List instances
        for name, adapter in self._instances.items():
            scanners.append(adapter.get_metadata())
        
        # List classes (that haven't been instantiated yet)
        for name, adapter_class in self._adapters.items():
            if name not in self._instances:
                adapter = adapter_class()
                scanners.append(adapter.get_metadata())
        
        return scanners
    
    def get_by_category(self, category: ScannerCategory) -> list[ScannerAdapter]:
        """Get all scanners in a specific category"""
        scanners = []
        for name in self._adapters.keys() | self._instances.keys():
            adapter = self.get(name)
            if adapter and adapter.category == category:
                scanners.append(adapter)
        return scanners
    
    def get_by_kind(self, kind: ScannerKind) -> list[ScannerAdapter]:
        """Get all scanners of a specific kind"""
        scanners = []
        for name in self._adapters.keys() | self._instances.keys():
            adapter = self.get(name)
            if adapter and adapter.kind == kind:
                scanners.append(adapter)
        return scanners


# Global registry instance
scanner_registry = ScannerRegistry()


def register_scanner(name: str):
    """Decorator to register a scanner adapter"""
    def decorator(adapter_class: type[ScannerAdapter]):
        scanner_registry.register(name, adapter_class)
        return adapter_class
    return decorator
